detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    enabled: false

  Attribute:
    exclude:
      - Truemail#configuration
      - Truemail::Configuration#verifier_domain

  UtilityFunction:
    exclude:
      - Truemail::Configuration#email_valid?
