detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - Truemail::ConfigurationHelper#configuration_block
      - Truemail::Validate::Smtp#not_includes_user_not_found_errors

  TooManyStatements:
    exclude:
      - Truemail::Validate::Smtp::Request#run
      - Truemail::Validate::Smtp#run
      - Truemail::Validate::Mx#hosts_from_cname_records
      - Truemail::Configuration#initialize

  TooManyInstanceVariables:
    exclude:
     - Truemail::Configuration
     - Truemail::Validate::Smtp::Request

  Attribute:
    exclude:
      - Truemail::Configuration#whitelist_validation
      - Truemail::Configuration#smtp_safe_check
      - Truemail::Wrapper#attempts

  UtilityFunction:
    exclude:
      - Truemail::Validate::Smtp::Request#compose_from
      - Truemail::Validator#select_validation_type
      - Truemail::Validate::Base#configuration
      - Truemail::Validate::Mx#null_mx?
      - Truemail::Validate::Mx#a_record
      - Truemail::Audit::Base#verifier_domain
      - Truemail::Configuration#domain_matcher

  ControlParameter:
    exclude:
      - Truemail::GenerateEmailHelper#calculate_email_size
      - Truemail::Worker#success
      - Truemail#raise_unless
      - Truemail::Configuration#raise_unless
      - Truemail#determine_configuration

  FeatureEnvy:
    exclude:
      - Truemail::Validate::Smtp#not_includes_user_not_found_errors
      - Truemail::GenerateEmailHelper#prepare_user_name
      - Truemail::ConfigurationHelper#create_configuration

  NilCheck:
    exclude:
      - Truemail::Validator#result_not_changed?
