AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.6

Metrics/LineLength:
  Max: 140

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
