AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.4

Metrics/LineLength:
  Max: 140

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
